model: unet

hidden:
  num_blocks: 4
  num_bits: 16
  in_channels: 3
  out_channels: 3
  z_channels: 64
  normalization: 'group'
  activation: 'gelu'
  last_tanh: True

unet_very_tiny:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 8
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 4]
    last_tanh: True

unet_very_tiny_bw:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 1
    z_channels: 16
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4]
    last_tanh: True
    zero_init: True

unet_small_notanh:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 16
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4]
    last_tanh: False

unet:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 32
    num_blocks: 4
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True

unet_small2:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 16
    num_blocks: 8
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True
  
unet_small2_yuv:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 1
    out_channels: 1
    z_channels: 16
    num_blocks: 8
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True
  
unet_small2_yuv_idinit:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 1
    out_channels: 1
    z_channels: 16
    num_blocks: 8
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True
    id_init: True

unet_small2_bw:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 1
    z_channels: 16
    num_blocks: 8
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True

unet_bw:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 1
    z_channels: 32
    num_blocks: 4
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True

unet_notanh:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 32
    num_blocks: 4
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: False
  
unet_big:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 64
    num_blocks: 4
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]

vae_tiny:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 3
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 16
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 3
    ch: 16
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True


vae_tiny_yuv:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 1
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 16
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 1
    ch: 16
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True

vae_small:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 3
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 32
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 3
    ch: 32
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True


vae_small_yuv:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 1
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 32
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 1
    ch: 32
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True

vae_small_bw:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 3
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 32
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 1
    ch: 32
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True

vae_big:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 3
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 64
    ch_mult: [1, 1, 2, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 3
    ch: 64
    ch_mult: [1, 1, 2, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True
